version: '1'
services:
  cattakeout-mysql:
    build:
      context: ./
      dockerfile: ./db/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    container_name: cattakeout-mysql
    image: cattakeout-mysql
    ports:
      - 3306:3306
    volumes:
      - ./cattakeout-mysql:/var/lib/mysql
    command: --lower_case_table_names=1

  cattakeout-main:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    container_name: cattakeout-main
    image: cattakeout-main
    ports:
      - 8080:8080
    depends_on:
      - cattakeout-mysql
    links:
      - "cattakeout-mysql"