server:
  port: 8080
spring:
  application:
    #应用的名称，可选
    name: cat_take_out
  shardingsphere:
    datasource:
      names: master,slave
      # 主数据源
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.0.128:3306/cat_takeout?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: root
      # 从数据源
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.0.129:3306/cat_takeout?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: root
    masterslave:
      name: dataSource
      load-balance-algorithm-type: round_robin  #轮询
      master-data-source-name: master
      slave-data-source-names: slave
    props:
      sql:
        show: true  #开启sql显示
  main:
    allow-bean-definition-overriding: true  #允许bean覆盖，为了sharing与其他不冲突

  redis:
    database: 0
    host: 43.142.166.38
    port: 6379
    password: root
  cache:
    redis:
      time-to-live: 600000 #设置cache存活时间
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

cat:
  path: D:\img\